services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: admin_vote
      POSTGRES_PASSWORD: Jakarta48!
      POSTGRES_DB: evoting_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin_vote -d evoting_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: evoting_backend
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: admin_vote
      DB_PASSWORD: Jakarta48!
      DB_NAME: evoting_db
      AVALANCHE_RPC_URL: https://api.avax-test.network/ext/bc/C/rpc
      CONTRACT_ADDRESS: 0x9FCC44BCA018Cc6A994a62c7DBCaA56278422747
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
